os: linux
dist: xenial
language: r
r:
  - release
cache: packages
addons:
  apt:
    packages:
      - libv8-dev
script:
  - |
    R CMD build .
    travis_wait 30 R CMD check mkin_*.tar.gz
after_success:
  - travis_wait 30 Rscript -e 'covr::codecov()'
