os: linux
dist: xenial
language: r
r:
  - release
cache: packages
addons:
  apt:
    packages:
      - libv8-dev
r_packages:
  - mclust
script:
  - |
    R CMD build .
    R CMD check mrlocus_*.tar.gz
